### ISSUE TITLE
/usr/lib/ruby/2.3.0/net/http.rb:1561:in `addr_port': undefined method `+' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by TheRogue27** [dreadlocked/Drupalgeddon2#33]
on some hosts i get this
/usr/lib/ruby/2.3.0/net/http.rb:1561:in `addr_port': undefined method `+' for nil:NilClass (NoMethodError)
i cant figure out what this error relates to.
anyone have any ideea?

**Comment by dreadlocked** [comment]
Can you paste the command you are using to execute the script?
